pipeline {
  kafka {
    bootstrap-servers = "localhost:9092"
    bootstrap-servers = ${?KAFKA_BOOTSTRAP}
    topics {
      transactions = "transactions"
      clients = "clients"
      products = "products"
    }
    consumer-group = "spark-pipeline-group"
  }

  postgres {
    url = "jdbc:postgresql://localhost:5432/ecommerce"
    url = ${?POSTGRES_URL}
    user = "pipeline"
    user = ${?POSTGRES_USER}
    password = "pipeline123"
    password = ${?POSTGRES_PASSWORD}
    driver = "org.postgresql.Driver"
  }

  spark {
    app-name = "ECommerce-Data-Pipeline"
    master = "local[*]"
    checkpoint-dir = "output/checkpoints"
    trigger-interval = "10 seconds"
  }

  output {
    parquet-dir = "output/parquet"
    reports-dir = "output/reports"
  }

  demo {
    num-transactions = 500
    num-clients = 50
    num-products = 100
    batch-size = 50
    delay-ms = 200
  }
}
